{{ if .Values.confluent_operator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    kn: "knite-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: confluent
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/RuiEusebio/eks-confluent-operator.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ./releases/{{.Values.environment}}/values.yaml 
      ignoreMissingValueFiles: true  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{ end }}      