apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: "kn-bitnami-secrets"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.8.2
  destination:
    namespace: kube-system
    server: {{ .Values.dest_server }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true