{{ if .Values.martianbank.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: martianbank
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  labels:
    demo: "martianbank"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: martianbank
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/mamonteiro-microops-pt/martianbank.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}